# [START django_app]
service: default
runtime: python310
env: standard
entrypoint: gunicorn -b :$PORT chat_app.wsgi

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto

env_variables:
  SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
  DEBUG: "False"

runtime_config:
  python_version: 3