# [START django_app]
service: default
runtime: python310
env: standard
entrypoint: daphne -p :$PORT chat_app.asgi:application

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto

runtime_config:
  python_version: 3