# Generated by Django 5.0.2 on 2024-02-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="type",
            field=models.CharField(
                choices=[("Type 1", "type 1"), ("Type 2", "type 2")],
                help_text="Type of the account is required.",
                max_length=6,
            ),
        ),
    ]
