# Generated by Django 5.0.2 on 2024-02-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0002_alter_customuser_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="type",
            field=models.CharField(
                choices=[("Type 1", "type 1"), ("Type 2", "type 2")],
                help_text="Type of account determines access to chat rooms",
                max_length=6,
            ),
        ),
    ]
