name: Deploy to GAE

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Authenticate gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Connect to gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Gather Static Files
        run: |
          python manage.py collectstatic --noinput

      - name: Set up connection variables in app.yaml
        env:
          CLOUD_VPC_CONNECTOR_NAME: ${{ secrets.CLOUD_VPC_CONNECTOR_NAME }}
          CLOUD_SQL_INSTANCE_CONNECTION_NAME: ${{ secrets.CLOUD_SQL_INSTANCE_CONNECTION_NAME }}
        run: bash set_up_connections.sh

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          version: v1
          project_id: ${{ secrets.PROJECT_ID }}
          credentials: ${{ secrets.SERVICE_ACCOUNT }}